name: models
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Turskyi/flutter_life_coaching_ai

environment:
  sdk: ^3.5.0

dependencies:
  collection: any
  equatable: ^2.0.5
  flutter_translate: ^4.1.0
  formz: ^0.8.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.25.8
