name: Code Quality

on: [ push ]

jobs:
  check-code-quality-and-tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Write .env file to nested directory
        run: |
          mkdir -p core/repositories/authentication_repository
          echo "$ENV" | base64 -d > core/repositories/authentication_repository/.env
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Write env.g.dart file
        run: |
          cd core/repositories/authentication_repository
          dart run build_runner build --delete-conflicting-outputs
        shell: bash

      - name: Get packages
        run: flutter pub get

      - name: Check format errors
        run: dart format --set-exit-if-changed .

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Check lint errors
        run: flutter analyze .

      - name: Run tests with coverage and random order
        run: flutter test --coverage --test-randomize-ordering-seed random

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 9

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Turskyi/flutter_life_coaching_ai